[tool.poetry]
name = "class1"
version = "0.1.0"
description = ""
authors = ["Mislav PeriÄ‡ <mislav.peric@axilis.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
